/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package redesiii;

import java.awt.Color;
import java.io.File;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author cef
 */
public class InterfazInicio extends javax.swing.JFrame {

    /**
     * Creates new form InterfazInicio
     */
    public InterfazInicio() {
        super("Servedor de Verificación");

        initComponents();
        path.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ipRespaldo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonInicio = new javax.swing.JButton();
        path = new javax.swing.JTextField();
        esRespaldo = new javax.swing.JRadioButton();
        botonElegir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        campoCorreo = new javax.swing.JTextField();
        campoPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ipRespaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipRespaldoActionPerformed(evt);
            }
        });

        jLabel1.setText("IP Servidor de Respaldo");

        jLabel2.setText("Path Configuración");

        botonInicio.setText("Iniciar Servidor");
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });

        path.setText("archivo de configuración");
        path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathActionPerformed(evt);
            }
        });

        esRespaldo.setText("Es respaldo");
        esRespaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esRespaldoActionPerformed(evt);
            }
        });

        botonElegir.setText("Elegir");
        botonElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonElegirActionPerformed(evt);
            }
        });

        jLabel3.setText("Correo de Notificacion");

        campoCorreo.setText("redesiii2012@gmail.com");
        campoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCorreoActionPerformed(evt);
            }
        });

        campoPassword.setText("claveclave");
        campoPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPasswordActionPerformed(evt);
            }
        });

        jLabel4.setText("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonInicio)
                .addGap(218, 218, 218))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ipRespaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCorreo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esRespaldo)
                    .addComponent(botonElegir))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipRespaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(esRespaldo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonElegir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(botonInicio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ipRespaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipRespaldoActionPerformed
        verif_esresp = true;
    }//GEN-LAST:event_ipRespaldoActionPerformed

    private void pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathActionPerformed
    }//GEN-LAST:event_pathActionPerformed

    private void esRespaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esRespaldoActionPerformed

        if (ipRespaldo.isEditable()) {
            ipRespaldo.setEditable(false);
            ipRespaldo.setBackground(Color.LIGHT_GRAY);
            ipRespaldo.setText("");
        } else {
            ipRespaldo.setEditable(true);
            ipRespaldo.setBackground(Color.WHITE);
        }

    }//GEN-LAST:event_esRespaldoActionPerformed

    private void botonElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElegirActionPerformed
        JFileChooser selector = new JFileChooser();
        selector.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int resultado = selector.showOpenDialog(this);

        if (resultado == JFileChooser.CANCEL_OPTION) {
            return;
        }

        File archivo = selector.getSelectedFile();

        if (archivo == null || archivo.getName().compareTo("") == 0) {

            JOptionPane.showMessageDialog(this,
                    "Nombre de Archivo Incorrecto", "Nombre de Archivo Incorrecto", JOptionPane.ERROR_MESSAGE);

        } else {

            path.setText(archivo.getAbsolutePath());
            verif_path = true;

        }
    }//GEN-LAST:event_botonElegirActionPerformed

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        try {
            if (verif_path && campoPassword.getPassword().length > 0) {
                Servidor.path_config = path.getText();

                System.out.println("aki");

                if (!campoCorreo.getText().matches("[a-zA-Z]\\w*@\\w+\\.com")) {
                    JOptionPane.showMessageDialog(this,
                            "ERROR: Campo de correo con formato incorrecto", "Campo de correo con formato incorrecto", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                //if (esRespaldo.isSelected() && verif_esresp && !ipRespaldo.getText().matches("\\s*"))

                Servidor server = new Servidor(campoCorreo.getText(), traducirClave(campoPassword.getPassword()));
                if (!esRespaldo.isSelected()) {
                    if (ipRespaldo.getText() != null && ipRespaldo.getText().matches("(\\d){1,3}\\.(\\d){1,3}\\.(\\d){1,3}\\.(\\d){1,3}")) {
                        server.agregar_servidores_backup(ipRespaldo.getText());
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "ERROR: Campos obligatorios incompletos o con formato incorrecto", "Campos obligatorios incompletos o con formato incorrecto", JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                }




                InterfazPrincipal interfazP = new InterfazPrincipal(server);
                interfazP.setVisible(true);

            } else {

                JOptionPane.showMessageDialog(this,
                        "ERROR: Campos obligatorios incompletos", "Campos obligatorios incompletos", JOptionPane.ERROR_MESSAGE);

            }
        } catch (RemoteException ex) {
            Logger.getLogger(InterfazInicio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botonInicioActionPerformed

    private void campoPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPasswordActionPerformed

    private void campoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCorreoActionPerformed

    public String traducirClave(char[] clave) {
        String dec = "";
        for (char i : clave) {
            dec += i;
        }
        System.out.println("la clave es |" + dec + "|");
        return dec;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InterfazInicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonElegir;
    private javax.swing.JButton botonInicio;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JRadioButton esRespaldo;
    private javax.swing.JTextField ipRespaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField path;
    // End of variables declaration//GEN-END:variables
    private boolean verif_esresp = false;
    private boolean verif_path = false;
}
